[project]
name = "landtable_legacy"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "pydantic~=2.10.3",
]

[project.scripts]
landtable = "landtable_legacy.__main__:app"

[tool.setuptools]
py-modules = []

[tool.pyright]
venvPath = "."
venv = ".venv"
reportMissingModuleSource = false
reportUnusedImport = true

[tool.hatch.envs.default]
path = "./.venv/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
