[project]
name = "landtable"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "asyncpg~=0.30.0",
    "aetcd~=1.0.0a4",
    "pydantic~=2.10.3",
    "uvicorn~=0.32.1",
    "fastapi~=0.115.6",
    "typer-slim~=0.15.1",
    "click~=8.1.8",
    "rich~=13.9.4",
    "cuddly-dicts~=1.0.1",
    "pytest-asyncio~=0.25.3",
    "fastui~=0.7.0",
    "python-multipart>=0.0.20",
]

[project.entry-points."landtable.backends"]
# postgres = "landtable.backends.postgres_backend:PostgresBackend"
in_memory_v0 = "landtable.backends.in_memory:InMemoryDatabaseBackend"

[project.entry-points."landtable.auth"]
unsafe_allow_all_requests_i_know_what_i_am_doing = "landtable.auth.unsafe:UnsafeAuthenticationPlugin"
reject = "landtable.auth.reject:RejectAuthenticationPlugin"

[project.scripts]
landtable = "landtable.__main__:app"

[tool.setuptools]
py-modules = []

[tool.pyright]
reportMissingModuleSource = false
reportUnusedImport = true

[project.optional-dependencies]
tests = [
    "pytest~=8.3.4",
    "pytest-cov~=6.0.0",
    "pytest-asyncio~=0.25.3"
]
speedups = [
    "orjson~=3.10.15",
    "uvloop~=0.21.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
